name: elanel_asistencia_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  collection: ^1.19.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  http: ^1.4.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  markdown_toolbar: ^0.5.0
  mime: ^2.0.0
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  timeago_flutter: ^3.7.0
  timeline_tile: ^2.0.0
  vibration: ^3.1.3
  file_picker: ^10.2.0
  video_player: ^2.10.0

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
