name: elanel_asistencia_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  markdown_editor_plus: ^0.2.15
  markdown_toolbar: ^0.5.0
  timeago: ^3.7.1
  timeago_flutter: ^3.7.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
